jasypt:
   encryptor:
      password: ${jasyptpwd}
      algorithm: PBEWithMD5AndDES

server:
   port: 8083
   servlet:
      context-path: /gestion_presupuesto

tiempoHealthCheck:
   tiempo: 30000

spring:
   flyway:
      outOfOrder: true
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://localhost/gestion_presupuesto?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Bogota
      username: gestion_presupuesto
      password: mE4fLj6Ykl3IRWr5
      hikari:
         poolName: pool


